### ISSUE TITLE
Ownership inquiry from @est31

### ISSUE THREAD

**Issue by qnighy** [qnighy/yasna.rs#16]
I've heard via another channel that @est31 is willing to contribute to this project as a maintainer.

Honestly, I've already lost interests on this project and been procrastinating its maintenance. I'm sorry for that, but therefore I'm willing to give its ownership to someone who has more interests on it.

Some confirmations:

- Do you really consider it useful? I've not investigated its competitors, but there'll definitely be some. yasna.rs is just a byproduct of a personal experiment on implementing TLS (https://github.com/qnighy/crypt-impl-rust ).
- You want write access to this repository on GitHub and ownership of the crates.io registration, right?

**Comment by est31** [comment]
@qnighy I confirm, I've asked someone to reach out to you via slack. I would like to help out with maintaining this crate from now on. For this I'd like to have write access on GitHub and ability to push crates.io releases.

I am using yasna in [rcgen](https://github.com/est31/rcgen), but need a few more features than yasna provides. I could send them as PRs but seeing that there are many unreviewed PRs in the queue I thought that it would be better if I just asked for maintainership transfer directly.

As for comparing with the other ASN.1 crates on crates.io. If you search for "asn.1" on crates.io you get the following:

* [raisin](https://crates.io/crates/raisin) last release in 2015. Doesn't even have repo or documentation links, and rustdoc is empty. [This](https://docs.rs/raisin/0.0.1/src/raisin/lib.rs.html#1-3) is the source code. Nuff said, it's a placeholder :).
* [asn1](https://crates.io/crates/asn1) last release in 2015. Only supports writing, not parsing. It can write some things that yasna atm can't write, but I need e.g. implicit tags, which this library can't do. Also, it's severely lacking in documentation.
* [asnom](https://crates.io/crates/asnom) with last release in 2017. Supports parsing and writing. The most serious contender so far. It's API feels more arcane to me though than the yasna API, maybe that's only due to the missing documentation. And although it can write more stuff than the `asn1` crate, it seems seems to be missing the ability to write implicit tags as well (yasna can do it).
* [asn1-cereal](https://crates.io/crates/asn1-cereal) with last release in 2016. Claims to support writing only in the crates.io description but looking at the rustdoc it seems to support both parsing and writing. Very fancy with a derive macro and so on, so I think you have to define your own structs and call the derive macro to be able to serialize them as ASN.1. So it's another very serious contender. I couldn't find anything big that yasna can do that asn1-cereal can't (null support isn't big) but I personally prefer the API style of yasna. Also, yasna has much better docs.

Also, yasna has the most downloads compared to the other crates, as it's used by the trussh-keys crate.

Also, there seems to be more interest in the community into this crate compared to the asn1-cereal and asnom crates: there has only been one PR to the asn1-cereal crate, zero to the asnom crate, while yasna has 6 non-author PRs.

So I'd say that asnom and asn1-cereal are both big contenders but yasna has more community interest, much better docs and more users than the two other crates. That's why I believe that it's the best choice.

**Comment by qnighy** [comment]
@est31 Thank you for the clear explanation, I've not imagined that my crate became so popular. Sure, I've invited you to the GitHub repo and the crates.io registry. And again, thank you for your great help.

cc: @P-E-Meunier who has the biggest dependency to yasna.

**Comment by est31** [comment]
Thanks, gotten invitations for both crates.io and github. This is resolved now!
